In [2]:
# Create a new notebook: notebooks/01_numpy_fundamentals.ipynb
import numpy as np
import time
print("NumPy: The Foundation of AI Mathematics")
print("=" * 40)
# Understanding why NumPy matters for AI
print("Python Lists vs NumPy Arrays Performance:")
# Create large datasets (typical in AI)
python_list = list(range(1000000))
numpy_array = np.array(python_list)
# Test mathematical operations speed
start_time = time.time()
python_result = [x * 2 for x in python_list]
python_time = time.time() - start_time
start_time = time.time()
numpy_result = numpy_array * 2
numpy_time = time.time() - start_time
print(f"Python list multiplication: {python_time:.4f} seconds")
print(f"NumPy array multiplication: {numpy_time:.4f} seconds")
print(f"NumPy is {python_time/numpy_time:.1f}x faster! 🚀")

NumPy: The Foundation of AI Mathematics
Python Lists vs NumPy Arrays Performance:
Python list multiplication: 0.0132 seconds
NumPy array multiplication: 0.0009 seconds
NumPy is 14.9x faster! 🚀


In [4]:
# Essential NumPy operations for AI development

# 1. Array Creation - Building Blocks of AI Data
print("\n1. Array Creation Techniques:")

# From lists (common when loading data)
data_list = [1, 2, 3, 4, 5]
arr_from_list = np.array(data_list)
print(f"From list: {arr_from_list}")

# Zeros and ones (neural network initialization)
zeros_matrix = np.zeros((3, 4))  # 3 rows, 4 columns
ones_matrix = np.ones((2, 3))
print(f"Zeros matrix:\n{zeros_matrix}")

# Random arrays (essential for AI model initialization)
random_weights = np.random.randn(3, 3)  # Normal distribution
random_data = np.random.random((2, 4))   # Uniform distribution
print(f"Random weights (normal):\n{random_weights}")
print(f"Random data (uniform):\n{random_data}")

# Ranges (useful for creating indices and sequences)
sequence = np.arange(0, 10, 2)  # Start, stop, step
linspace_vals = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print(f"Sequence: {sequence}")
print(f"Linspace: {linspace_vals}")


1. Array Creation Techniques:
From list: [1 2 3 4 5]
Zeros matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Random weights (normal):
[[-0.77050247 -0.01665525  2.82010558]
 [ 1.61055394 -0.70174333  2.12839926]
 [-0.77574628  1.67388832  0.8551964 ]]
Random data (uniform):
[[0.59266926 0.24188209 0.88643591 0.92352018]
 [0.53467209 0.1971271  0.90219525 0.43769647]]
Sequence: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [5]:
# 2. Array Operations - The Heart of AI Computations
print("\n2. Essential Array Operations:")

# Mathematical operations (used in every AI algorithm)
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Element-wise operations
addition = arr1 + arr2
multiplication = arr1 * arr2
power = arr1 ** 2

print(f"Addition: {addition}")
print(f"Multiplication: {multiplication}")
print(f"Power: {power}")

# Matrix operations (core of neural networks)
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Dot product (matrix multiplication) - fundamental in AI
dot_product = np.dot(matrix_a, matrix_b)
print(f"Matrix multiplication:\n{dot_product}")

# Broadcasting (allows operations between different sized arrays)
scalar = 10
broadcasted = matrix_a + scalar  # Adds 10 to every element
print(f"Broadcasting (matrix + scalar):\n{broadcasted}")


2. Essential Array Operations:
Addition: [ 6  8 10 12]
Multiplication: [ 5 12 21 32]
Power: [ 1  4  9 16]
Matrix multiplication:
[[19 22]
 [43 50]]
Broadcasting (matrix + scalar):
[[11 12]
 [13 14]]


In [6]:
# 3. Statistical Operations - Data Analysis for AI
print("\n3. Statistical Operations:")

# Create sample data (simulating model performance metrics)
model_scores = np.array([0.85, 0.87, 0.83, 0.89, 0.86, 0.84, 0.88, 0.85])

# Descriptive statistics
mean_score = np.mean(model_scores)
std_score = np.std(model_scores)
median_score = np.median(model_scores)
min_max = np.min(model_scores), np.max(model_scores)

print(f"Model Performance Analysis:")
print(f"Mean accuracy: {mean_score:.3f}")
print(f"Standard deviation: {std_score:.3f}")
print(f"Median accuracy: {median_score:.3f}")
print(f"Min/Max accuracy: {min_max}")

# Multi-dimensional statistics
data_2d = np.random.randn(100, 3)  # 100 samples, 3 features
column_means = np.mean(data_2d, axis=0)  # Mean of each feature
row_means = np.mean(data_2d, axis=1)     # Mean of each sample

print(f"Feature means: {column_means}")
print(f"Sample means shape: {row_means.shape}")


3. Statistical Operations:
Model Performance Analysis:
Mean accuracy: 0.859
Standard deviation: 0.019
Median accuracy: 0.855
Min/Max accuracy: (np.float64(0.83), np.float64(0.89))
Feature means: [-0.04513199 -0.0792848  -0.15418964]
Sample means shape: (100,)


In [7]:
# 4. Array Reshaping and Indexing - Data Preparation for AI
print("\n4. Array Reshaping and Indexing:")

# Reshaping (essential for preparing data for neural networks)
original_data = np.arange(24)
reshaped_2d = original_data.reshape(4, 6)  # 4 rows, 6 columns
reshaped_3d = original_data.reshape(2, 3, 4)  # 3D tensor

print(f"Original: {original_data}")
print(f"2D reshape:\n{reshaped_2d}")
print(f"3D shape: {reshaped_3d.shape}")

# Advanced indexing (data filtering and selection)
large_dataset = np.random.randn(1000, 5)  # 1000 samples, 5 features

# Boolean indexing (filtering data based on conditions)
positive_values = large_dataset > 0
outliers = np.abs(large_dataset) > 2  # Values more than 2 standard deviations

print(f"Positive values percentage: {np.mean(positive_values)*100:.1f}%")
print(f"Outliers percentage: {np.mean(outliers)*100:.1f}%")

# Fancy indexing (selecting specific rows/columns)
selected_samples = large_dataset[[0, 10, 100, 500]]  # Select specific rows
selected_features = large_dataset[:, [0, 2, 4]]       # Select specific columns

print(f"Selected samples shape: {selected_samples.shape}")
print(f"Selected features shape: {selected_features.shape}")


4. Array Reshaping and Indexing:
Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2D reshape:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
3D shape: (2, 3, 4)
Positive values percentage: 50.7%
Outliers percentage: 4.5%
Selected samples shape: (4, 5)
Selected features shape: (1000, 3)


In [8]:
# 5. Linear Algebra Operations - Neural Network Mathematics
print("\n5. Linear Algebra for AI:")

# Simulating a simple neural network forward pass
# Input layer (3 features) -> Hidden layer (4 neurons) -> Output layer (2 classes)

# Input data (batch of 5 samples, 3 features each)
X = np.random.randn(5, 3)

# Weight matrices (randomly initialized like in real neural networks)
W1 = np.random.randn(3, 4) * 0.1  # Input to hidden weights
b1 = np.zeros((1, 4))              # Hidden layer bias
W2 = np.random.randn(4, 2) * 0.1  # Hidden to output weights
b2 = np.zeros((1, 2))              # Output layer bias

# Forward pass computation
hidden_layer = np.dot(X, W1) + b1  # Linear transformation
hidden_activation = np.maximum(0, hidden_layer)  # ReLU activation
output_layer = np.dot(hidden_activation, W2) + b2

print(f"Input shape: {X.shape}")
print(f"Hidden layer shape: {hidden_layer.shape}")
print(f"Output shape: {output_layer.shape}")
print(f"Sample output: {output_layer[0]}")

# Matrix properties (useful for understanding AI algorithms)
symmetric_matrix = np.array([[1, 2], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(symmetric_matrix)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")


5. Linear Algebra for AI:
Input shape: (5, 3)
Hidden layer shape: (5, 4)
Output shape: (5, 2)
Sample output: [-0.0009332   0.00304819]
Eigenvalues: [-0.23606798  4.23606798]
Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
